name: Scheduled Data Builder

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '16 6,8,9,10,13 * * *'
jobs:
  build:
    name: Convert csv to data.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: 'feature/#177-update-converter'
      - name: Download a file
        uses: carlosperate/download-file-action@v1.0.3
        id: download_csv
        with:
            file-url: 'https://isc-okinawa.org/opendata/470007_okinawa_covid19_patients.csv'
            file-name: 'cases.csv'
            location: 'tool/downloads'
      - name: Print the file path
        run: |
          echo "The file was downloaded to ${{ steps.download_csv.outputs.file-path }}"
          tail ${{ steps.download_csv.outputs.file-path }}
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "tool/downloads/summary.csv, tool/downloads/cases.csv"
      - name: Run composer install
        run: |
          cd tool
          composer install
      - name: Convert csv to data.json
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          echo All files exists!
          php tool/convert.php
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate:deploy
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tool/downloads
          git add data
          git commit -m "[Scheduled BOT] Update cases.csv, data.json"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'feature/#177-update-converter'
